config/routes.rb
Rails.application.routes.draw do
  resources :login_links, only: [:new, :create, :show]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resource :signup, only: [:new, :create]
  get "/login", to: "sessions#new", as: "login"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"

  get "pages/landing"

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#landing"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    @password_reset = PasswordResetToken.new
  end

  def create
    @password_reset = PasswordResetToken.new(password_reset_params)
    @password_reset.save
    UserMailer.password_reset_token(@password_reset.user).deliver_later

    flash[:notice] = "A link to reset your password has been sent to your email."
    redirect_to root_url
  end

  def edit
    @password_reset = PasswordResetToken.find_by_valid_token(params[:id])
    if @password_reset && @password_reset.user
      @user = @password_reset.user
    else
      flash[:alert] = "Your password reset link is not valid."
      redirect_to new_password_reset_path
    end
  end

  def update
    @password_reset = PasswordResetToken.find_by_valid_token(params[:id])
    if @password_reset && @password_reset.user
      if @password_reset.user.update(user_params)
        @password_reset.expire!
        flash[:notice] = "Your password has been updated."
        redirect_to root_url
      else
        flash.now[:alert] = "There was an error updating your password."
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:error] = "Your password reset link is not valid."
      redirect_to new_password_reset_path
    end
  end

  private

  def password_reset_params
    params.require(:password_reset_token).permit(:email)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= render "pages/shared/header" %>
<div class="container flex flex-row items-center justify-center">
  <div class="my-20">
    <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
      <div class="flex flex-col space-y-2 text-center">
        <h1 class="text-2xl font-semibold tracking-tight">Update Your Password</h1>
        <% if @user.errors.any? %>
          <div class="text-left">
            <%= render_alert variant: :error, title: "Failed to Update Password" do %>
              <% @user.errors.full_messages.each do |message| %>
                <p><%= message %></p>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="grid gap-6">
        <%= render_form_for(@user, url: password_reset_path, method: :patch) do |f| %>
          <div class="grid gap-2">
            <div class="grid gap-1">
              <div class="grid gap-1">
                <%= f.label :password, class: "sr-only" %>
                <%= f.password_field :password, placeholder: "Your password...",
                                              autocomplete: "current-password" %>
              </div>
              <div class="grid gap-1">
                <%= f.label :password, class: "sr-only" %>
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password...",
                                              autocomplete: "current-password" %>
              </div>
              <%= f.submit "Reset Password" %>
            </div>
          </div>
        <% end %>
        <p class="text-muted-foreground px-8 text-center text-sm">
          By clicking continue, you agree to our
          <a
          class="hover:text-primary underline underline-offset-4"
          href="/terms">Terms of Service</a>
          and
          <a
          class="hover:text-primary underline underline-offset-4"
          href="/privacy">Privacy Policy</a>.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<%= render "pages/shared/header" %>
<div class="container flex flex-row items-center justify-center">
  <div class="my-20">
    <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
      <div class="flex flex-col space-y-2 text-center">
        <h1 class="text-2xl font-semibold tracking-tight">Reset Your Password</h1>
      </div>
      <div class="grid gap-6">
        <%= render_alert variant: :error, title: "Email and/or password not found." if flash[:alert] %>
        <%= render_form_for(@password_reset,  url: password_resets_path) do |f| %>
          <div class="grid gap-2">
            <div class="grid gap-1">
              <%= f.label :email, class: "sr-only" %>
              <%= f.email_field :email, placeholder: "name@example.com",
                                        autocomplete: :email,
                                        autocorrect: "email",
                                        autocapitalize: "none" %>
            </div>
            <%= f.submit "Reset Password" %>
          </div>
        <% end %>
      </div>
      <p class="text-muted-foreground px-8 text-center text-sm">
        Or try <%= link_to "logging into your account", login_path, class: "underline" %>.
      </p>
      <p class="text-muted-foreground px-8 text-center text-sm">
        By clicking continue, you agree to our
        <a
          class="hover:text-primary underline underline-offset-4"
          href="/terms">Terms of Service</a>
        and
        <a
          class="hover:text-primary underline underline-offset-4"
          href="/privacy">Privacy Policy</a>.
      </p>
    </div>
  </div>
</div>