config/routes.rb
Rails.application.routes.draw do
  resources :login_links, only: [:new, :create, :show]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resource :signup, only: [:new, :create]
  get "/login", to: "sessions#new", as: "login"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"

  get "pages/landing"

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#landing"
end

app/controllers/login_links_controller.rb
class LoginLinksController < ApplicationController
  def show
    @login_token = LoginToken.find_by_valid_token(params[:id])
    if @login_token && @login_token.user
      @login_token.expire!
      sign_in(@login_token.user)
      redirect_to root_path, notice: "You have successfully logged in!"
    else
      redirect_to new_login_link_path, alert: "Your login link has expired. Please request a new one."
    end
  end

  def new
    @login_token = LoginToken.new
  end

  def create
    @login_token = LoginToken.new(login_token_params)
    @login_token.save
    UserMailer.login_token(@login_token.user).deliver_later
    redirect_to root_path, notice: "Login link sent!"
  end

  private

  def login_token_params
    params.require(:login_token).permit(:email)
  end
end

app/helpers/login_links_helper.rb
module LoginLinksHelper
end

app/views/login_links/new.html.erb
<%= render "pages/shared/header" %>
<div class="container flex flex-row items-center justify-center">
  <div class="my-20">
    <div class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[350px]">
      <div class="flex flex-col space-y-2 text-center">
        <h1 class="text-2xl font-semibold tracking-tight">Request Login Link</h1>
      </div>
      <div class="grid gap-6">
        <%= render_alert variant: :error, title: "Email and/or password not found." if flash[:alert] %>
        <%= render_form_for(@login_token, url: login_links_path) do |f| %>
          <div class="grid gap-2">
            <div class="grid gap-1">
              <%= f.label :email, class: "sr-only" %>
              <%= f.email_field :email, placeholder: "name@example.com",
                                        autocomplete: :email,
                                        autocorrect: "email",
                                        autocapitalize: "none" %>
            </div>
            <%= f.submit "Send Login Link" %>
          </div>
        <% end %>
      </div>
      <p class="text-muted-foreground px-8 text-center text-sm">
        Or try <%= link_to "logging into your account", login_path, class: "underline" %>.
      </p>
      <p class="text-muted-foreground px-8 text-center text-sm">
        By clicking continue, you agree to our
        <a
          class="hover:text-primary underline underline-offset-4"
          href="/terms">Terms of Service</a>
        and
        <a
          class="hover:text-primary underline underline-offset-4"
          href="/privacy">Privacy Policy</a>.
      </p>
    </div>
  </div>
</div>